server:
  port: 8080

spring:
  application:
    name: language-exchange-platform
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/language_exchange_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tzy235899
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: ${SPRING_MAIL_HOST:smtp.qq.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME:"470459064@qq.com"}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
      mail.smtp.ssl.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE:true}
      mail.smtp.starttls.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
  sql:
    init:
      mode: always
      encoding: UTF-8

app:
  demo-mode: false
  mail:
    from: ${APP_MAIL_FROM:${SPRING_MAIL_USERNAME:}}
